### ISSUE TITLE
Boolean assign error

### ISSUE THREAD

**Issue by DarkRedman** [Vyraax/BirdLang#13] opened 2020-06-29 19:55 UTC
```js
var mel = PI / 4
manuel = PI * 10
var manuel = mel > 10
```

The last line raises an error :

```js
terminate called after throwing an instance of 'std::bad_variant_access'
  what():  std::get: wrong index for variant
Abandon (core dumped)
```

**Comment by galactic-dust** [comment] 2020-06-29 19:56
Ok i'll take a look !

**Comment by galactic-dust** [comment] 2020-06-29 20:15
The Issue is now fixed!

**Closed as completed by galactic-dust** 2020-06-29 20:15 UTC
Labels: bug
